### ISSUE TITLE
rohdice producing empty output file

### ISSUE THREAD

**Issue by malawsky** [ZhiGroup/ROH-DICE#1]
Hello,

I am trying to run ROH-DICE and it is producing an empty output file. I made sure all SNPs are biallelic, 100% genotyping rate, and vcf was properly compressed. I also tried making minimum number of people 1 to see if it is because there are no roh clusters in my data, but the output was still empty.

**Comment by ardalan-n** [comment]
Hi,

Please note that the python code assumes that input data are phased and unphased sites are skipped. However, the algorithm does not use phasing information at all. If your data are unphased (separated by '/' instead of '|' in the VCF file), you can simply change line 94 in the script vcf_reader.py to:
`site_values = self.inter_vals[i].replace("\n", '').split("/")`



Best,
Ardalan
